### ISSUE TITLE
Interdependencies in mono repo

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-mkc#22]
When reference another mono-repo nested project, we download it from the github instead of using a local path.

![image](https://user-images.githubusercontent.com/4175913/117527776-5b2a2f80-af83-11eb-8d5b-cac28c98afc1.png)

**Comment by mmoskal** [comment]
I think this is by design - you need to specify `links` in `mkc.json`. Reopen if I'm confused.
