### ISSUE TITLE
don't build nested pxt_modules

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-mkc#23]
the cli goes into pxt_modules and tries to build those

![image](https://user-images.githubusercontent.com/4175913/118750665-add1da00-b814-11eb-98ac-003e531d774a.png)

**Comment by mmoskal** [comment]
fixed a while ago https://github.com/microsoft/pxt-mkc/commit/1c34c8d0d8ac33d773b0e3f0748175a9fb13face
