### ISSUE TITLE
add dependency command

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-mkc#36]
Add depenencies, update dependencies commands.

User won't get the formatting right.

**Comment by mmoskal** [comment]
yeah, `mkc add jacdac` could use makecode cloud extension search; if it finds more than 1 package, then maybe we print them all out and exit with error? or ask the user which one they want (option 1, 2, or 3 ?)

otherwise `mkc add microsoft/pxt-jacdac` would be good too
