### ISSUE TITLE
After bump, ping cloud to refresh caches

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-mkc#4]
In the client we do,

```
            await pxt.github.listRefsAsync(parsed.slug, "tags", true, true);
```

**Comment by mmoskal** [comment]
doesn't this work for you https://github.com/microsoft/pxt-mkc/blob/master/src/bump.ts#L139 ? 
it should be automatic.

**Comment by pelikhan** [comment]
Ooops my ad. You already covered this!
